pulumi_state_splitter: GitHub Actions workflow: set up poetry cache explicitly
instead of using the caching feature of action/setup-python, as it
needs to have the poetry binary in place:
https://github.com/actions/setup-python/issues/765
and I do not want to install poetry twice for two
Python versions.

This is to resolve
https://github.com/house-reliability-engineering/pulumi/pull/1/checks#step:3:14 :

```
 Error: Unable to locate executable file: poetry. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
```