pulumi_state_splitter: tests: test that unsplitting does not explode on non-existant stacks specified
We need this to work so that we can actually run `pulumi stack new`.

The test is currently failing:

```console
filip@dell1:~/git/github.com/house-reliability-engineering/pulumi/utilities/pulumi_state_splitter$ ./run-tests.sh
..............E........................E...............
======================================================================
ERROR: test_single_program (tests.test_integration.TestPulumiIntegration.test_single_program)
Pulumi integration test with one Pulumi program.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/filip/.local/share/uv/python/cpython-3.14.2-linux-x86_64-gnu/lib/python3.14/unittest/mock.py", line 1898, in _inner
    return f(*args, **kw)
  File "/home/filip/git/github.com/house-reliability-engineering/pulumi/utilities/pulumi_state_splitter/tests/test_integration.py", line 138, in test_single_program
    with unsplitter:
         ^^^^^^^^^^
  File "/home/filip/git/github.com/house-reliability-engineering/pulumi/utilities/pulumi_state_splitter/pulumi_state_splitter/split.py", line 164, in __enter__
    state_dir.load()
    ~~~~~~~~~~~~~~^^
  File "/home/filip/git/github.com/house-reliability-engineering/pulumi/utilities/pulumi_state_splitter/pulumi_state_splitter/split.py", line 64, in load
    with self._state_path.open() as f:
         ~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/filip/.local/share/uv/python/cpython-3.14.2-linux-x86_64-gnu/lib/python3.14/pathlib/__init__.py", line 771, in open
    return io.open(self, mode, buffering, encoding, errors, newline)
           ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpf8ui10lx/test-project/test-stack/state.yaml'

======================================================================
ERROR: test_unsplitter_some_stacks_1 (tests.test_split.TestUnsplitter.test_unsplitter_some_stacks_1)
Testing `Unsplitter` with specified stacks [with *extra=(StackName(project='test-project-1', stack='missing-stack'),)].
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/filip/git/github.com/house-reliability-engineering/pulumi/utilities/pulumi_state_splitter/.venv/lib/python3.14/site-packages/parameterized/parameterized.py", line 620, in standalone_func
    return func(*(a + p.args), **p.kwargs, **kw)
  File "/home/filip/git/github.com/house-reliability-engineering/pulumi/utilities/pulumi_state_splitter/tests/test_split.py", line 377, in test_unsplitter_some_stacks
    with pulumi_state_splitter.split.Unsplitter(
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        backend_dir=self._tmp_dir,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
        ],
        ^^
    ):
    ^
  File "/home/filip/git/github.com/house-reliability-engineering/pulumi/utilities/pulumi_state_splitter/pulumi_state_splitter/split.py", line 164, in __enter__
    state_dir.load()
    ~~~~~~~~~~~~~~^^
  File "/home/filip/git/github.com/house-reliability-engineering/pulumi/utilities/pulumi_state_splitter/pulumi_state_splitter/split.py", line 64, in load
    with self._state_path.open() as f:
         ~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/filip/.local/share/uv/python/cpython-3.14.2-linux-x86_64-gnu/lib/python3.14/pathlib/__init__.py", line 771, in open
    return io.open(self, mode, buffering, encoding, errors, newline)
           ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpt6jke63v/test-project-1/missing-stack/state.yaml'

----------------------------------------------------------------------
Ran 55 tests in 18.883s

FAILED (errors=2)
Name                                    Stmts   Miss  Cover   Missing
---------------------------------------------------------------------
pulumi_state_splitter/__init__.py           1      0   100%
pulumi_state_splitter/cli.py               47      0   100%
pulumi_state_splitter/fs.py                 8      0   100%
pulumi_state_splitter/model.py             37      0   100%
pulumi_state_splitter/split.py            111      0   100%
pulumi_state_splitter/state_file.py        46      0   100%
pulumi_state_splitter/stored_state.py      30      0   100%
---------------------------------------------------------------------
TOTAL                                     280      0   100%
filip@dell1:~/git/github.com/house-reliability-engineering/pulumi/utilities/pulumi_state_splitter$
```